Parameters:
  userPoolName:
    Default: FlyJetOnlineUserPool
    Type: String
  clientName:
    Default: FlyJetOnlineClient
    Type: String
  identityPoolName:
    Default: FlyJetOnlineIdentityPool
    Type: String

Resources:
  FlyJetOnlineUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AutoVerifiedAttributes:
        - email
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 7
      UserPoolName:
        Ref: userPoolName
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
        - AttributeDataType: String
          Name: phone_number
          Required: true
      UsernameAttributes:
        - email

  FlyJetOnlinePoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName:
        Ref: clientName
      GenerateSecret: false
      UserPoolId:
        Ref: FlyJetOnlineUserPool
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH

  AgentsGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Group all agents
      GroupName: Agents
      RoleArn: !GetAtt AgentsRole.Arn
      UserPoolId: !Ref FlyJetOnlineUserPool

  AgentsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref FlyJetOnlineIdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": authenticated

      Policies:
        - PolicyName: FlyJetOnline-ApiGateway-Access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - execute-api:Invoke
                  - lambda:InvokeFunction
                Resource: "*"

  FlyJetOnlineIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId:
            Ref: FlyJetOnlinePoolClient
          ProviderName: !GetAtt FlyJetOnlineUserPool.ProviderName
          ServerSideTokenCheck: true
      IdentityPoolName:
        Ref: identityPoolName

#  FlyJetOnlineIdentityRoleAtt:
#    Type: AWS::Cognito::IdentityPoolRoleAttachment
#    Properties:
#      IdentityPoolId: !Ref FlyJetOnlineIdentityPool
#      RoleMappings: '"Fn::GetAtt\": [\"FlyJetOnlineUserPool\", \"ProviderName\"] : { \"Type\":\"Token\",\"AmbiguousRoleResolution\":\"Deny\"}"'

Outputs:
  FlyJetOnlineUserPoolAuthorizer:
    Description: Cognito User Pool Arn
    Value: !GetAtt FlyJetOnlineUserPool.Arn
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolID
  FlyJetOnlineCognitoIdentityID:
    Description: Cognito Identity Pool ID
    Value: !Ref FlyJetOnlineIdentityPool
    Export:
      Name: !Sub ${AWS::StackName}-UserIdentityPoolId
