AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >
  FlyOnline Serverless Application

Parameters:
  FoIdentityStack:
    Type: String
    Default: FoIdentity

Globals:
  Function:
    Timeout: 60
    Runtime: go1.x
    MemorySize: 512
    AutoPublishAlias: dev
    Environment:
      Variables:
        DATABASE_TABLE: FlyOnlineDB

Resources:
  FlyOnlineApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: FlyOnlineApi
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,DELETE,PUT'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: AWS_IAM
        #Authorizers:
        #  FoAuth:
        #    UserPoolArn:
        #      Fn::ImportValue:
        #        Fn::Sub: ${FoIdentityStack}-UserPoolID
        #    Identity:
        #      Header: Authorization

  GetItem:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: ./
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:GetRecords
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
              Resource: !GetAtt FlyOnlineDB.Arn
      Events:
        GetItem:
          Type: Api
          Properties:
            Path: /item
            Method: GET
            RestApiId: !Ref FlyOnlineApi

  FlyOnlineDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ItemId
          AttributeType: S
        - AttributeName: TicketId
          AttributeType: S
      KeySchema:
        - AttributeName: ItemId
          KeyType: HASH
        - AttributeName: TicketId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: FlyOnlineDB
